import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#363e53",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        "inverse-primary": "#a8c8ff",
        "tertiary-fixed": "#dae2fd",
        "on-primary-fixed": "#001b3c",
        "on-secondary-container": "#54647a",
        "tertiary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#004689",
        "on-tertiary-fixed": "#131b2e",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        secondary: "#505f76",
        "on-surface-variant": "#424751",
        "primary-fixed": "#d5e3ff",
        "surface-container": "#eceef0",
        error: "#ba1a1a",
        "on-primary-container": "#afccff",
        primary: "#003e7a",
        "surface-container-highest": "#e0e3e5",
        "surface-container-high": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-surface": "#191c1e",
        "secondary-container": "#d0e1fb",
        "on-tertiary-container": "#c3cae4",
        background: "#f7f9fb",
        "outline-variant": "#c2c6d3",
        "on-secondary-fixed": "#0b1c30",
        surface: "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a8c8ff",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-tint": "#175ead",
        "tertiary-container": "#4d556b",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        outline: "#727783",
        "on-primary": "#ffffff",
        "primary-container": "#0055a4",
        "secondary-fixed-dim": "#b7c8e1",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#38485d",
        "inverse-on-surface": "#eff1f3",
        "on-background": "#191c1e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "12px",
        base: "4px",
        margin: "16px",
        sm: "6px",
        xs: "2px",
        lg: "16px",
        xl: "24px",
        gutter: "12px",
      },
      fontFamily: {
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "data-mono": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "title-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "data-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
